apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizations-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizations
  template:
    metadata:
      labels:
        app: organizations
    spec:
      containers:
        - image: cesarmarti/badminton-app-organizations
          name: organizations
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 40
            periodSeconds: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 40
            periodSeconds: 3
            timeoutSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: organizations
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: organizations