kumuluzee:
  name: badmiton-app-organizations-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BadmintonAppUsersDS
      connection-url: jdbc:postgresql://database-1.ctekqcytce4y.eu-central-1.rds.amazonaws.com/badminton
      username: postgres
      password: postgres

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="a4826a9e-5e6c-4a5e-a291-999edc93cdb5-ls.logit.io"
                                      port="12787" protocol="udp">
                                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="debug" />
                                          <AppenderRef ref="logstash" level="info" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'

  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/BadmintonAppUsersDS
      disk-space-health-check:
        threshold: 100000000
      etcd-health-check:
        connection-url: http://20.85.253.39:2379/health

  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://20.85.253.39:2379

  discovery:
    cluster: 1
    etcd:
      hosts: http://20.85.253.39:2379
      ttl: 30
      ping-interval: 5

  metrics:
    web-instrumentation:
      - name: organizations-endpoint
        url-pattern: /v1/organizations/*
rest-properties:
  maintenance-mode: false
  broken: false